### ISSUE TITLE
problem with underscored and polymorphic (scope)

### ISSUE THREAD

**Issue by zgid123** [RobinBuschmann/sequelize-typescript#740] opened 2020-02-07 19:03 UTC
**Versions**
- sequelize: 5.21.3
- sequelize-typescript: 1.1.0
- typescript: 3.7.3

**I'm submitting a ...** 
[ x] bug report
[ ] feature request

I have two models

```ts
@Table({
  paranoid: true,
  timestamps: true,
  underscored: true,
  tableName: 'products',
})
class Product extends Model<Product> {
  @HasMany(() => Media, {
    foreignKey: 'resourceId',
    scope: {
      resourceType: 'Product',
    },
  })
  public media?: Media[];
}

export default Product;
```

```ts
@Table({
  timestamps: true,
  underscored: true,
  tableName: 'media',
})
class Media extends Model<Media> {
  @Column({
    type: DataType.UUIDV1,
  })
  public resourceId!: string;

  @Column
  public resourceType!: string;
}

export default Media;
```

When I use `findAndCountAll`

```ts
const a = await global.models.Product.findAndCountAll({
    include: [global.models.Media],
  });
```

The first time I run the code, I will get the error `media.resourceType does not exist`. It should be `media.resource_type`.

Here the full query
```
SELECT count("Product"."id") AS "count" FROM "products" AS "Product" LEFT OUTER JOIN "media" AS "media" ON "Product"."id" = "media"."resource_id" AND "media"."resourceType" = 'Product' WHERE ("Product"."deleted_at" IS NULL);
Executing (default): SELECT "Product"."id", "media"."id" AS "media.id", "media"."resource_id" AS "media.resourceId", "media"."resource_type" AS "media.resourceType" FROM "products" AS "Product" LEFT OUTER JOIN "media" AS "media" ON "Product"."id" = "media"."resource_id" AND "media"."resource_type" = 'Product' WHERE ("Product"."deleted_at" IS NULL)
``` 

It seems the first query will face this problem. I run the `findAndCountAll` usage above the second time, I can receive the correct data

**Comment by RobinBuschmann** [comment] 2020-02-08 11:20
Hey @zgid123, thanks for reporting. This seems to be a sequelize issue. I reproduced this behaviour with sequelize only as well:
```js
  const sequelize = new Sequelize('sqlite::memory:');
  const Product = sequelize.define('Product', {}, {
    paranoid: true,
    timestamps: true,
    underscored: true,
    tableName: 'products',
  });
  const Media = sequelize.define('Media', {
    resourceType: DataTypes.STRING,
    resourceId: DataTypes.STRING,
  }, {
    timestamps: true,
    underscored: true,
    tableName: 'media',
  });
  Product.hasMany(Media, {
    foreignKey: 'resourceId',
    scope: {
      resourceType: 'Product',
    },
  });
  await sequelize.sync({force: true});

  await Product.findAndCountAll({include: [Media]});
```
As work around for now you can use `scope: {resource_type: 'Product' }` instead of`scope: {resourceType: 'Product' }`

Can you create an issue on https://github.com/sequelize/sequelize using my example above?

**Comment by zgid123** [comment] 2020-02-08 11:22
@RobinBuschmann I'm using your case too. If that's the case, let me create an issue for sequelize. Thanks for your quick reply

**Comment by RobinBuschmann** [comment] 2020-02-08 11:41
@zgid123 Yeah, would be cool if you could create an issue on https://github.com/sequelize/sequelize. Thank you!

**Comment by RobinBuschmann** [comment] 2020-03-14 07:19
Closing this in favour of https://github.com/sequelize/sequelize/issues/11916

**Closed by RobinBuschmann** 2020-03-14 07:19 UTC
