### ISSUE TITLE
vscode intellisense broke again ?

### ISSUE THREAD

**Issue by libvirtadept** [RobinBuschmann/sequelize-typescript#728] opened 2020-01-08 01:22 UTC
**Versions**

- sequelize: 5.12.2
- sequelize-typescript: 1.1.0
- typescript 3.7.4
- vscode: 1.41

**I'm submitting a ...** 

[x] bug report
[ ] feature request

Hello, 
This issue opened only due to previous same issue was closed
I think it is returning of bug with intellisense like here https://github.com/RobinBuschmann/sequelize-typescript/issues/333

**Actual behavior:**
![image](https://user-images.githubusercontent.com/57712891/71942449-53f7e380-31ce-11ea-9bb9-222021cda5f7.png)

**Expected behavior:**
Normal autocomplete for fieds and so on

**Steps to reproduce:**
Just open example project with vscode.
https://github.com/RobinBuschmann/sequelize-typescript-example

**Comment by RobinBuschmann** [comment] 2020-01-11 13:19
Duplicate of #726 

Since version 1.0.0 sequelize-typescript uses the official typings provided by sequelize. These typings just don't provide typechecking for create and where options. So this feature need to be implemented in sequelize

**Comment by libvirtadept** [comment] 2020-01-11 13:44
Hi, @RobinBuschmann 
Thank you for answer! Waiting for the fix from sequelize side :)

**Comment by capdilla** [comment] 2020-11-17 14:13
I found a solution for this, is not the best but it solve the problem 

```ts
//user.model.ts
@Table
export default class User extends Model<User> {
  @Column({ })
  _id: string;

  @Column({})
  firstName: string;

  @Column({})
  lastName: string;

  @Column({})
  age: number;
}

```


```ts
type Fields<T> = Omit<T, keyof Pick<Model<any>, keyof Model<any>>>;

export type IUser = Fields<User>;
```
this helper is going to remove all the fields of Model and only will keep the fields of the model so then you can call it like is in the image

![image](https://user-images.githubusercontent.com/15254223/99399943-a32a9c80-28e6-11eb-95a6-c3090b452ef2.png)

**Comment by Divlo** [comment] 2021-01-17 21:38
We close this issue since it's a duplicate of #726 and `sequelize-typescript` is only a npm library, it has nothing to do with `vscode`.

**Closed by Divlo** 2021-01-17 21:38 UTC
