### ISSUE TITLE
Question/Issue: Type Hinting Oddly Delayed

### ISSUE THREAD

**Issue by xlxAciDxlx** [RobinBuschmann/sequelize-typescript#403] opened 2018-07-02 17:53 UTC
So I'm having a rather weird issue. When typing out model properties (example `email` for a `User` model), the type/property hint (`em` => `email: string` popup suggestion) do not appear. Is there some sort of type hinting that's not fully being put in place as would be expected?

```ts
@Column({
	unique: true
})
email: string;
```

I expect `email` to be suggested when trying to run `User.create`, however it doesn't show up until I fully type out `email`.

**Comment by MatthiasKunnen** [comment] 2018-07-04 21:09
I would be handy to know your environment in order to reproduce/resolve this. Which IDE are you using, are there any plugins that might have an effect on type hinting, which version of TypeScript are you using, ...

I'm using Webstorm 2018.1.5 and don't have this issue.

**Comment by xlxAciDxlx** [comment] 2018-07-04 21:11
I'm using Visual Studio Code, I think with the standard TypeScript extension. My TypeScript version is `2.9.2`

**Comment by MatthiasKunnen** [comment] 2018-07-04 21:45
And this is when you use `Model.build({email: 'email@example.com'})` or `new Model({email: 'email@example.com'})`? I've had more accurate type hints with the latter.

**Comment by xlxAciDxlx** [comment] 2018-07-04 22:03
Apparently, the issue is that using the shorthand `Model.build` or `Model.create` don't show the typing suggestions. However, doing `new Model(...)` works as expected.

**Comment by MatthiasKunnen** [comment] 2018-07-05 00:12
Based on the typings, I can't really see anything that could cause this.
```TypeScript
constructor(values?: FilteredModelAttributes<T>, options?: IBuildOptions);
static build<T extends Model<T>>(this: (new () => T), record?: FilteredModelAttributes<T>, options?: IBuildOptions): T;
```
The `this: (new () => T)` is a combination of a [this parameter](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters) and a [constructor type](http://blakeembrey.com/articles/2015/04/typescript-constructor-of-type/). It basically says that in the `create` function, `this` will refer to a class that has a constructor which takes no arguments and returns an object of type `T`. It basically means that inside the `Person.build()` method, calling `new this()` will return a `Person`.

Since the _this parameter_ does (read: should) not matter for type hinting, the remaining thing is the generics definition `<T extends Model<T>>`. This is the same as the instance type and has to be repeated because static methods can't use the instance type arguments. Concluding: the types seem exactly the same. Although I might be wrong, I don't see any issue on this library's end.

The thing is, I can't reproduce your issue in Webstorm nor in vscode. Can you try clearing your cache and restarting your compiler service?

**Comment by MatthiasKunnen** [comment] 2018-07-05 16:14
For VS Code, I think restarting should suffice

**Comment by xlxAciDxlx** [comment] 2018-07-05 16:15
I tried clearing the Editor History, restarting, removing some extensions (though none of them were related to TypeScript) - all to no avail.

**Comment by MatthiasKunnen** [comment] 2018-07-26 12:09
Did you resolved this issue? Maybe updating VS Code helps?

**Comment by xlxAciDxlx** [comment] 2018-08-16 13:51
Unfortunately, this still occurs. I've updated VS Code, updated TypeScript, downgraded, etc, etc- all to no avail. I even fully uninstalled+reinstalled VS Code to no avail. I'd provide my source code which would undoubtedly help diagnose my issue, but unfortunately, the project's not published. Are there any specific things I might be able to post that might help track down what my issue could be? Maybe my TSLint, TSConfig, etc?

**Comment by MatthiasKunnen** [comment] 2018-08-16 14:27
What you could perhaps is trying to reproduce this issue in Webstorm (free trial version). If the problem occurs there, we know it's the code, libraries, etc ... not the IDE.

**Comment by xlxAciDxlx** [comment] 2018-08-16 14:35
I'll try that out and get back to you, thanks :)

**Comment by xlxAciDxlx** [comment] 2018-08-16 14:53
Alright, so on the good side (I guess) the issue's definitely something in VS Code. Type hinting works as expected in Webstorm, even with just opening my project folder in it, going to my API and opening my `auth` route.

Now to figure out what I need to do to fix the problem in VS Code...

**Comment by MatthiasKunnen** [comment] 2018-08-16 15:16
If it doesn't work with no extensions installed and works in another IDE, I think it might be time to create an issue in the VS code repository. Explain the problem, link to this issue and maybe they can help.

**Comment by RobinBuschmann** [comment] 2018-11-15 09:05
@xlxAciDxlx Regarding your comment
> ...the good side (I guess) the issue's definitely something in VS Code..

So this has nothing to do with sequelize-typescript, right? Can we close this issue then?

**Comment by MatthiasKunnen** [comment] 2018-11-15 14:16
@RobinBuschmann, to my understanding, this issue occurs under specific circumstances which are present in sequelize-typescript but sequelize-typescript is not at fault. Meaning, yes, this issue can be closed.

**Closed** 2018-11-15 15:14 UTC
