### ISSUE TITLE
composite key and foreign keys

### ISSUE THREAD

**Issue by ShintaroNippon** [RobinBuschmann/sequelize-typescript#537] opened 2019-02-04 12:17 UTC
HI there i'm trying to use sequelize typescript in order to create a composite unique key

this is my code:

```
@Column({
		field: 'is_default',
		type: DataType.BOOLEAN,
		unique: 'active_unique',
	})
	public isDefault: boolean;
	// ForeignKeys
	@ForeignKey(() => Profile)
	@Column({
		allowNull: false,
		field: 'profile_id',
		type: DataType.STRING(255),
		unique: 'active_unique',
	})

```

But I'm having problems in creation new rows with different Profile and online unique in isDefault...

Does any can help please?

Thanks in advance
Carlos Vieira

**Comment by blankstar85** [comment] 2019-02-04 19:57
Can you post more of your code? looks like your missing your second column value, i'm guessing should be profileID?
What is the error, are you getting a foreign key constraint? Are you getting a index error ( unique, already exists). 
How are you setting up the database?

**Comment by RobinBuschmann** [comment] 2019-02-07 08:15
Hey @ShintaroNippon, as @blankstar85 stated, we need some more information (error message, best would be an example repo, which reproduces the issue) in order to help.

**Comment by ShintaroNippon** [comment] 2019-02-11 11:24
Hi, thanks by the reply..
Yes, its profileID...
And yes its 
"What is the error, are you getting a foreign key constraint? Are you getting an index error ( unique, already exists)."

That's what is happening.
THanks

**Comment by ShintaroNippon** [comment] 2019-02-11 11:56
```

// PrimaryKey
@PrimaryKey
@ForeignKey(() => Address)
@Column({
	allowNull: false,
	field: 'address_id',
	type: DataType.INTEGER,
})
public addressId: number;

// Fields
@Column({
	field: 'vat_number',
})
public vatNumber: string;

@Column({
	field: 'is_default',
	type: DataType.BOOLEAN,
	unique: 'active_unique',
})
public isDefault: boolean;

// ForeignKeys
@ForeignKey(() => Profile)
@Column({
	allowNull: false,
	field: 'profile_id',
	unique: 'active_unique',
})
public profileId: string;

// Belongs
@BelongsTo(() => Address)
public address: Address;

```
Additional information:

- The logging is showing the constraint UNIQUE `active_unique` (`is_default`), but this should be UNIQUE `active_unique` (`is_default`, `profile_id`).

- In the logging also is showing the constraint UNIQUE `AddressId_profileId_unique` (`address_id`, `profile_id`), but I don't know why it is happening.

**Comment by RobinBuschmann** [comment] 2019-02-17 18:57
@ShintaroNippon For foreign keys you have to define it within the association options like so:

```ts
@BelongsTo(() => Profile, {
    foreignKey: {
      unique: '* active_unique'
    }
  })
```

Hope this helps!

**Comment by RobinBuschmann** [comment] 2019-02-26 08:45
@ShintaroNippon Does this help? Can we close this issue now?

**Comment by ShintaroNippon** [comment] 2019-02-26 09:39
HI, sorry, 
yes indeed... its working.
Many thanks
Carlos Vieira

**Closed** 2019-02-26 09:40 UTC
