### ISSUE TITLE
Problem with "addHook" - Error: Model not initialized

### ISSUE THREAD

**Issue by cvh23** [RobinBuschmann/sequelize-typescript#102] opened 2017-08-18 18:52 UTC
If I do this:
```
    const sequelize =  new Sequelize({
      host: 'localhost',
      dialect: 'postgres',
      name: 'testdb',
      username: 'testuser',
      password: '',
      define: {
        timestamps: true,
        underscored: true,
        paranoid: true,
      }
    });

    // convert camelCase to snake_case
    sequelize.addHook('beforeDefine', (attributes, options) => {
      console.log(options);

      Object.keys(attributes).forEach(key => {
        attributes[key].field = decamelize(key);
      });
    });

    sequelize.addModels([ User ]);

    sequelize.sync();
```
I get this error:
```
Error: Model not initialized: "User" needs to be added to a Sequelize instance before "inspect" can be called.
    at checkInitialization (.../node_modules/sequelize-typescript/lib/models/BaseModel.js:63:23)
    at Function._target.(anonymous function) [as inspect] (.../node_modules/sequelize-typescript/lib/models/BaseModel.js:33:21)
    at formatValue (util.js:349:36)
    at formatProperty (util.js:790:15)
    at util.js:650:12
    at Array.map (native)
    at formatObject (util.js:649:15)
:
.
```

If I remove `console.log(options)` in the code, everything is fine. What I wanted to do: I want to modify "options" as well, so that table names are also decamelized (snake case).

**Comment by RobinBuschmann** [comment] 2017-08-18 20:31
Hey @cvhberger. Can you try to add the model first before calling addHook? Hopefully this should fix it.

**Comment by cvhberger** [comment] 2017-08-19 15:51
@RobinBuschmann Than I get no error, because the hook is not executed any more.

**Comment by thecritic** [comment] 2017-08-19 18:19
Same here. Are the hook decorators going to be added in v1 ? Can you give an example of how to successfully add a hook (without the decorators, since they are not available in sub [beta]1.0) ?

**Comment by RobinBuschmann** [comment] 2017-08-19 19:33
Ah ok, I didn't get it in the first place - it is the 'beforeDefine' hook. In that case this seems to be a bug.

But probably we can find a workaround for now. What are you trying to achieve @cvhberger?

@thecritic The hook decorators will be in the next release :) for now you can add a hook after the model is initialized, which means after it is added to a Sequelize instance while instantiating a Sequelize object or adding it via `addModels`. So for example `User.beforeCreate(...)`

**Comment by cvhberger** [comment] 2017-08-19 21:27
@RobinBuschmann I want to have table and column names **by default** in "snake case" (underscores), not in camel case. According names in Typescript model should still be in camel case. A discussion on a Sequelize issue recommended this way (with the beforeDefine hook). And it works. And also in sequelize-typescript as long as I dont try to access the second hook parameter "options", which I would need to modify the table name. In the given example above, it's currently just rewriting column names.

**Comment by RobinBuschmann** [comment] 2017-08-20 09:33
@cvhberger For now you could implement this with sequelize-typescript features like this:

```typescript
import {getOptions, addOptions, getAttributes, addAttributeOptions} from 'sequelize-typescript/lib/services/models';

yourModelClasses.forEach(modelClass => {
  const target = modelClass.prototype;
  const options = getOptions(target);
  const attributes = getAttributes(target);

  addOptions(target, {
    tableName:  decamelize(options.tableName)
  });

  Object.keys(attributes).forEach(key => {
    addAttributeOptions(target, key, {field: decamelize(key)});
  });

});
```
(Currently have no possibility to test this but it should work)

**Comment by thecritic** [comment] 2017-08-20 09:47
@RobinBuschmann Maybe a stupid/unrelated question but how do I check if the model has been added to sequelize ? I'm quite new to NodeJS/Sequelize and I'd want to define the hook in the Model class itself where I think it belongs. Any suggestions on how to do this ? Currently I get the error "Model needs to be added to a Sequelize instance before addHook can be called".

**Comment by RobinBuschmann** [comment] 2017-08-20 20:10
@thecritic You're absolutely right, that the definition of hooks belongs to the models. But for now - which means with the current sequelize-typescript version available on npm - you can only do this:

```typescript
// User.ts
export class User extends Model<User> {}

// index.ts
import {Sequelize} from 'sequelize-typescript';

const sequelize = new Sequelize({
   modelPaths: ['path/to/models']
}); // or adding the Models after initialized, but before adding the hook like sequelize.addModels([User]);

User.beforeCreate(...);

// The order of execution is important!
```

For the **next release** you will be able to define the hooks via decorators:
```typescript
// User.ts
export class User extends Model<User> {

  @BeforeCreate
  static doSomeStuff(...) {}
}
```

**Comment by thecritic** [comment] 2017-08-20 22:54
@RobinBuschmann Alright thanks! I'll have a workaround in place for now until the hooks decorators are done. Got an ETA (estimate) for v1 ?

**Comment by RobinBuschmann** [comment] 2017-08-21 10:39
@thecritic I will try to make a beta release on next weekend, which includes the hooks feature (this can be installed then via `npm install sequelize-typescript@0.5.0-beta.0`)

**Comment by thecritic** [comment] 2017-08-21 12:58
@RobinBuschmann Awesome thanks, take your time. Great work btw. Really in love with this project.

**Comment by cvhberger** [comment] 2017-08-22 02:32
@RobinBuschmann As the models are not added at a central point in my application, but in different parts, I had to write a wrapper method named "addModel" (see below).

```typescript
  async addModel(model) {
    const target = model.prototype;
    const options = getOptions(target);
    const attributes = getAttributes(target);

    addOptions(target, {
      tableName: decamelize(options.tableName)
    });

    Object.keys(attributes).forEach(key => {
      addAttributeOptions(target, key, {field: decamelize(key)});
    });

    await this.sequelize.addModels([ model ]);

    this.sequelize.sync();
  }
```

Table and columns are now converted correctly (I can see the correct SQL output on console, when Sequelize syncs the model), but adding data doesn't work anymore:
```typescript
      const user = new User({
        username: 'user@example.com',
        password: ''
      });

      user.save();
```

If I remove 
```typescript
    addOptions(target, {
      tableName: decamelize(options.tableName)
    });
```
and add the tableName directly at the Table decorator, it works. But I want a generic way. Maybe you have an idea how to solve that?

**Comment by RobinBuschmann** [comment] 2017-08-22 10:20
@cvhberger which error message occurs when you try to adding data?

**Comment by cvhberger** [comment] 2017-08-22 13:15
There is no error message, just silence :)

**Comment by RobinBuschmann** [comment] 2017-08-22 13:34
Ok, I will try to reproduce this in next weekend. Unfortunately I don't have time to investigate this earlier.

**Comment by RobinBuschmann** [comment] 2017-08-26 12:52
@cvhberger My [suggestion](https://github.com/RobinBuschmann/sequelize-typescript/issues/102#issuecomment-323574219) works perfectly well for me.

What I can say is, that you should not add the models separately if they have relations between each other. `sequelize-typescript` tries to solve associations synchronously right after they are added. That's why they need to be added at once.

**Comment by RobinBuschmann** [comment] 2019-02-25 12:41
Is working with `sequelize-typescript@1.0.0-alpha.8`

**Closed by RobinBuschmann** 2019-02-25 12:41 UTC
Labels: bug
