### ISSUE TITLE
Error in Model class compiling typescript 

### ISSUE THREAD

**Issue by nevyen** [RobinBuschmann/sequelize-typescript#390] opened 2018-06-10 05:36 UTC
Hey when I'm compiling my project I get this error message from typescript compiler: 

```
 error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```
It is thrown from the Model class by using Omit. So maybe this error only happens on my PC or it is a general problem. 

Any help is welcome.

**Comment by FinalFrag** [comment] 2018-06-11 08:08
I'm getting the same thing. Excluding node_modules in tsconfig.json doesn't seem to work either :/

```
node_modules/sequelize-typescript/lib/utils/types.d.ts:9:16 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

9     [P in Diff<keyof T, K>]: T[P];
```

**Comment by RobinBuschmann** [comment] 2018-06-11 18:17
Duplicate of #379

Fixed in `sequelize-typescript@next`

**Closed** 2018-06-11 18:17 UTC
Labels: duplicate
