### ISSUE TITLE
 Error(`Foreign key for "${relatedClass.name}" is missing `

### ISSUE THREAD

**Issue by hansyulian** [RobinBuschmann/sequelize-typescript#751] opened 2020-03-13 08:18 UTC
**Versions**
- sequelize: 5.21.3
- sequelize-typescript: 1.1.0
- typescript: 3.8.3

**I'm submitting a ...** 
[x ] bug report
[ ] feature request

**Actual behavior:**
Error: Foreign key for "User" is missing on "Session".

**Expected behavior:**
Following the guide on https://www.npmjs.com/package/sequelize-typescript#one-to-many, it should be working

**Steps to reproduce:**
- i just tried to follow to make association documented in https://www.npmjs.com/package/sequelize-typescript#one-to-many

**Related code:**

User.ts
```ts
@Table({
  timestamps: true,
})
export class User extends Model<User> {
  @Column({
    primaryKey: true,
    defaultValue: uuid
  })
  public id!: string;

  @Column
  public name!: string;

  @Column({
    unique: true,
  })
  public email!: string;

  @Column
  public get password(): string {
    return this.getDataValue('password');
  };

  public set password(value: string) {
    this.setDataValue('password', hashPassword(value));
  }

  @Column({
    defaultValue: 'normal'
  })
  public role!: UserRole;

  @Column({
    defaultValue: 'active'
  })
  public status!: UserStatus;

  @Column
  public resetPasswordToken?: string;

  @Column
  public resetPasswordTokenExpiry?: Date;

  @HasMany(() => Session)
  public sessions!: Session[];
}
```

Session.ts
```ts

@Table({
  timestamps: true,
})
export class Session extends Model<Session> {
  @Column
  public secret!: string;

  @Column({
    defaultValue: () => new Date().getTime() + getConfig('sessionAgeMs')
  })
  public expiry!: Date;

  @ForeignKey(() => User)
  @Column
  public userId!: string;

  @BelongsTo(() => User, 'userId')
  public user!: User;
}
```

**Comment by tobias47n9e** [comment] 2020-03-13 19:37
Possible duplicate of https://github.com/RobinBuschmann/sequelize-typescript/issues/748 ?

**Comment by RobinBuschmann** [comment] 2020-03-14 12:46
Hey @hansyulian, thanks for reporting. At what point do you receive this error? Just with the definition of the models or when trying to use them? I tried both and it is working very well for me. Can you provide an example repo which reproduces the issue?

**Comment by RobinBuschmann** [comment] 2020-04-10 09:21
Closing this due to inactivity

**Closed by RobinBuschmann** 2020-04-10 09:21 UTC

**Comment by umdstu** [comment] 2020-06-16 17:15
Versions

sequelize: 5.21.13
sequelize-typescript: 1.1.0
typescript: 3.7.2

I'm having this exact issue- new issue or re-open?

Models look good, no typescript errors anywhere. It happens when I go to start the service and it runs the compiled code. I'll provide anything you need, thanks in advance.

User.ts: HasMany Workflow
Workflow.ts: BelongsTo User

`node ./dist/server.js`

```
./node_modules/sequelize-typescript/dist/associations/foreign-key/foreign-key-service.js:23
        throw new Error(`Foreign key for "${relatedClass.name}" is missing ` +
        ^

Error: Foreign key for "User" is missing on "Workflow".
    at Object.getForeignKeyOptions(./node_modules/sequelize-typescript/dist/associations/foreign-key/foreign-key-service.js:23:15)
    at HasAssociations.getSequelizeOptions(./node_modules/sequelize-typescript/dist/associations/has/has-association.js:17:52)
```

**Comment by EdByrnee** [comment] 2020-11-04 19:46
Same issue here, everything set up 

> Versions
> 
> sequelize: 5.21.13
> sequelize-typescript: 1.1.0
> typescript: 3.7.2
> 
> I'm having this exact issue- new issue or re-open?
> 
> Models look good, no typescript errors anywhere in editor. It happens when I go to start the service and it runs the compiled code. I'll provide anything you need, thanks in advance.
> 
> User.ts: HasMany Workflow
> Workflow.ts: BelongsTo User
> 
> `node ./dist/server.js`
> 
> ```
> ./node_modules/sequelize-typescript/dist/associations/foreign-key/foreign-key-service.js:23
>         throw new Error(`Foreign key for "${relatedClass.name}" is missing ` +
>         ^
> 
> Error: Foreign key for "User" is missing on "Workflow".
>     at Object.getForeignKeyOptions(./node_modules/sequelize-typescript/dist/associations/foreign-key/foreign-key-service.js:23:15)
>     at HasAssociations.getSequelizeOptions(./node_modules/sequelize-typescript/dist/associations/has/has-association.js:17:52)
> ```

Any luck figuring this out??

I'm having the same issue and it's sending me crazy, all my models are set up correctly but I'm stilling getting the Foreign Key missing error!! :

**Comment by EdByrnee** [comment] 2020-11-04 20:13
> **Versions**
> 
> * sequelize: 5.21.3
> * sequelize-typescript: 1.1.0
> * typescript: 3.8.3
> 
> **I'm submitting a ...**
> [x ] bug report
> [ ] feature request
> 
> **Actual behavior:**
> Error: Foreign key for "User" is missing on "Session".
> 
> **Expected behavior:**
> Following the guide on https://www.npmjs.com/package/sequelize-typescript#one-to-many, it should be working
> 
> **Steps to reproduce:**
> 
> * i just tried to follow to make association documented in https://www.npmjs.com/package/sequelize-typescript#one-to-many
> 
> **Related code:**
> 
> User.ts
> 
> ```ts
> @Table({
>   timestamps: true,
> })
> export class User extends Model<User> {
>   @Column({
>     primaryKey: true,
>     defaultValue: uuid
>   })
>   public id!: string;
> 
>   @Column
>   public name!: string;
> 
>   @Column({
>     unique: true,
>   })
>   public email!: string;
> 
>   @Column
>   public get password(): string {
>     return this.getDataValue('password');
>   };
> 
>   public set password(value: string) {
>     this.setDataValue('password', hashPassword(value));
>   }
> 
>   @Column({
>     defaultValue: 'normal'
>   })
>   public role!: UserRole;
> 
>   @Column({
>     defaultValue: 'active'
>   })
>   public status!: UserStatus;
> 
>   @Column
>   public resetPasswordToken?: string;
> 
>   @Column
>   public resetPasswordTokenExpiry?: Date;
> 
>   @HasMany(() => Session)
>   public sessions!: Session[];
> }
> ```
> 
> Session.ts
> 
> ```ts
> @Table({
>   timestamps: true,
> })
> export class Session extends Model<Session> {
>   @Column
>   public secret!: string;
> 
>   @Column({
>     defaultValue: () => new Date().getTime() + getConfig('sessionAgeMs')
>   })
>   public expiry!: Date;
> 
>   @ForeignKey(() => User)
>   @Column
>   public userId!: string;
> 
>   @BelongsTo(() => User, 'userId')
>   public user!: User;
> }
> ```

Did you manage to figure this out? Going crazy trying to debug

**Comment by ColtraneNadler** [comment] 2021-03-02 17:50
Did anyone figure this out? It works when I use nodemon, but not when I try to build :(

**Comment by yuvalt** [comment] 2022-02-05 00:45
Cleaning the "build" directory and re-building it, fixed it for me 🤷🏼‍♂️

**Comment by Ebsyr** [comment] 2024-09-08 16:42
> Cleaning the "build" directory and re-building it, fixed it for me

how did you do that? I have the same issue and i have no idea what to do
