### ISSUE TITLE
Sorting Included Models

### ISSUE THREAD

**Issue by oderayi** [RobinBuschmann/sequelize-typescript#567] opened 2019-03-12 16:30 UTC
Sequelize provides a way to sort `include`d models like so:

```Javascript
db.Page.findAll({
  include: [{
    model: db.Gallery
    include: [{
      model: db.Artwork
    }]
  }],
  order: [
    [ db.Gallery, 'orderColumn', 'DESC' ],
    [ db.Gallery, db.ArtWork, 'orderColumn', 'DESC' ]
  ]
})
```

I couldn't seem to achieve this using sequelize-typescript.

**Comment by RobinBuschmann** [comment] 2019-03-17 17:42
@oderayi What is the error you're facing?

**Comment by michael-go** [comment] 2019-03-20 16:21
👋 @RobinBuschmann we are converting our codebase now to use this awesome lib, and also currently struggle with the `order` throwing an exception.
 
Don't know if it's the same issue @oderayi has, but we pinpointed it to this condition being false in https://github.com/sequelize/sequelize/blob/v3/lib/dialects/abstract/query-generator.js#L828
```js
if (item instanceof Model) {
```
where `item` is the model passed as the first parameter to the `order` array, and the debugger displays it as `[object SequelizeModel:User]`.  seems like `SequelieModel` isn't `instanceof Model` ...

Note we are using Sequelize v3

**Comment by RobinBuschmann** [comment] 2019-03-20 16:30
@michael-go  Can your provide an example repo, which reproduces the issue? Would be much easier to investigate this for me. Thank you :)

**Comment by michael-go** [comment] 2019-03-24 10:09
@RobinBuschmann thanks for the quick response 🙇 
reproduced the issue here: https://github.com/michael-go/sequelize-ts-order-issue

**Comment by RobinBuschmann** [comment] 2019-03-26 20:22
@michael-go It is a bug and like you said: `item` is not an instance of `Model`. There is no way to fix this (see below*), but there is another way to order by `Org`. Use `{model: Org, as: 'Org'}` instead of just `Org`:
```ts
    order: [
      [{model: Org, as: 'Org'}, 'name', 'ASC']
    ],
```

*This is because how `sequelize@3` handles instances and model definitions: They are different constructor functions("classes"), namely: `Instance` and `Model` (Since `sequelize@4` it is represented in one class `Model`). `sequelize-typescript.Model` only extends `sequelize@3.Instance`, that's why `item instanceof Model` is false.

**Comment by RobinBuschmann** [comment] 2019-04-28 09:34
Closing this since it cannot be fixed. Use https://github.com/RobinBuschmann/sequelize-typescript/issues/567#issuecomment-476833404 as a workaround

**Closed by RobinBuschmann** 2019-04-28 09:34 UTC
Labels: wontfix

**Comment by samuelt1** [comment] 2019-07-08 05:15
@RobinBuschmann 's answer fixes the issue inside of the findAll sort of query, but I am using a  defaultScope to pull the includes with the order like this:
```@DefaultScope({
    include: [
        {model: ()=>ServiceProvider},
        {model: ()=>Insurance},
        {model: ()=>Utility},
        {model: ()=>Mortgage},
        {model: ()=>User},
        {as: 'address',model: ()=>Address},
    ],
    order: [
        [ {model: ServiceProvider, as: 'serviceProviders'}, 'id', 'ASC'],
        [ {model: Insurance, as: 'insurances'}, 'id', 'ASC'],
        [ {model: Utility, as: 'utilities'}, 'id', 'ASC'],
        [ {model: Mortgage, as: 'mortgages'}, 'id', 'ASC'],
    ],
})```

this will throw the error:
```
/app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:80
        .reduce((acc, key) => {
         ^
TypeError: Class constructor ServiceProvider cannot be invoked without 'new'
    at /app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:83:32
    at Array.reduce (<anonymous>)
    at resolveModelGetter (/app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:80:10)
    at /app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:89:24
    at Array.reduce (<anonymous>)
    at resolveModelGetter (/app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:80:10)
    at /app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:89:24
    at Array.reduce (<anonymous>)
    at resolveModelGetter (/app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:80:10)
    at /app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:89:24
    at Array.reduce (<anonymous>)
    at Object.resolveModelGetter (/app/node_modules/sequelize-typescript/dist/model/shared/model-service.js:80:10)
    at resolveDeprecatedScope (/app/node_modules/sequelize-typescript/dist/scopes/scope-service.js:90:72)
    at /app/node_modules/sequelize-typescript/dist/scopes/scope-service.js:59:25
    at Array.forEach (<anonymous>)
    at Object.exports.resolvesDeprecatedScopes (/app/node_modules/sequelize-typescript/dist/scopes/scope-service.js:59:10)
    at /app/node_modules/sequelize-typescript/dist/scopes/scope-service.js:13:17
    at Array.forEach (<anonymous>)
    at Object.resolveScopes (/app/node_modules/sequelize-typescript/dist/scopes/scope-service.js:12:12)
    at Sequelize.addModels (/app/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:37:25)
    at new Sequelize (/app/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:18:22)
    at Object.<anonymous> (/app/src/server/core/sequelize.ts:6:3)```

my sequelize.ts looks like this:
```import { Sequelize } from 'sequelize-typescript';
import { ServerConfiguration } from '../../config';
import { Op } from 'sequelize';

export const sequelize =
  new Sequelize({
    operatorsAliases: Op,
    database: ServerConfiguration.database,
    username: ServerConfiguration.username,
    password: ServerConfiguration.password,
    host: ServerConfiguration.host,
    dialect: 'postgres',
    models: [__dirname + '/../models'],
  });
```
