### ISSUE TITLE
$count return type is this instead of number

### ISSUE THREAD

**Issue by samanmohamadi** [RobinBuschmann/sequelize-typescript#290] opened 2018-02-03 10:32 UTC
https://github.com/RobinBuschmann/sequelize-typescript/blob/4302356c452bfc27b1ba0117cc8abae170dd1e35/lib/models/Model.d.ts#L452

**Comment by RobinBuschmann** [comment] 2018-02-03 20:51
Hey @samanmohamadi, thanks for reporting, but it is a duplicate of #247

**Closed** 2018-02-09 22:54 UTC
Labels: duplicate
