### ISSUE TITLE
Completion inside @Table({}) and @Column({}) does not work

### ISSUE THREAD

**Issue by devoto13** [RobinBuschmann/sequelize-typescript#530] opened 2019-01-28 19:02 UTC
Let's say I try to define a model with some indexes:

```
@Table({
  ind<cursor>
})
class User extends Model<User> {
}
```

There is no completion available at the `<cursor>`. This happens, because of the [signature](https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/annotations/Table.ts#L6) of the `Table` function, which accepts `any` parameter in one of the overloads. TypeScript always coerces `whatever | any` into `any`, so missing completion makes sense.

While for `@Table` annotation it may be fixed by changing `any` to `Function` it won't work with `@Column` as the decorator on the field should actually accept `any`. One possible solution would be to stop supporting usage without `()` and force users to write `@Column()` and `@Table()` even when they don't pass any parameters.

Do you think it is a reasonable trade-off to force `()` on parameterless annotations for better completion or maybe have other ideas how to solve it?

**Comment by RobinBuschmann** [comment] 2019-01-30 07:05
Hey @devoto13 thanks for bringing this up. How does your tsconfig look like? 

I cannot reproduce your issue, since autocompletion is working for me very well. Actually the return type of the decorator should already solve what you described 🤔
```ts
export declare function Table(options: IDefineOptions): Function;
export declare function Table(target: any): void;
```

**Comment by devoto13** [comment] 2019-01-30 11:58
@RobinBuschmann In which editor did you try? I just noticed that WebStorm does something on top of the TypeScript language server, so it works there. It does not work in VS Code though. I have also checked the logs of TypeScript language server and it does return empty completion list in this case.

And here is a demo: https://github.com/devoto13/sequelize-completion

**Comment by RobinBuschmann** [comment] 2019-01-31 13:18
@devoto13 For @Table it works but for @Column, you're totally right. Nevertheless we should change it for both. The [official typings](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1370) for decorators are looking like this:
```ts
declare type PropertyDecorator = (target: Object, propertyKey: string | symbol) => void;
```
So we should use `Object` as well to be consistent (I checked it, it works as well). What do you think?

**Comment by devoto13** [comment] 2019-01-31 14:33
It still does not work for me.

Here is what I observe with below signature (only `valueOf` in the completion list):

```ts
export declare function Column(target: Object, propertyName: string, propertyDescriptor?: PropertyDescriptor): void;
```

![demo1](https://user-images.githubusercontent.com/823594/52060717-1544bc80-256d-11e9-9ef0-2fd901c0a489.gif)

And here is what I observe with this overload removed (list of possible properties to add, the desired behavior):

![demo2](https://user-images.githubusercontent.com/823594/52060770-37d6d580-256d-11e9-8efd-7d3f779b4954.gif)

Do you get these properties (`validate`, `values`, `defaultValue`) in the completion list if you replace `any` with `Object`? Then maybe I'm doing something wrong.

**Comment by RobinBuschmann** [comment] 2019-02-01 08:10
Hey @devoto13 I'm getting autocompletion with `target: Object`:

<img width="530" alt="bildschirmfoto 2019-01-31 um 17 00 07" src="https://user-images.githubusercontent.com/5270739/52110525-2f2fdf00-2601-11e9-8273-d84f01e887f4.png">

**Comment by RobinBuschmann** [comment] 2019-02-16 17:13
@devoto13 Did you get it to work with `target: Object`? Or do I do something wrong

**Comment by devoto13** [comment] 2019-02-16 23:14
No, it still did not work for me. I'll check with other colleagues on Monday to see if it works for them. Maybe we have different versions or plugins installed... Not sure what may be the reason for different results we get.

**Comment by devoto13** [comment] 2019-02-18 16:46
@RobinBuschmann I just checked with a colleague and he has the same results as I've reported in 
https://github.com/RobinBuschmann/sequelize-typescript/issues/530#issuecomment-459365660. We both use VS Code version 1.31.1.

Below are the exact steps of what we do, can you try it and describe what you do to get the completion working? Maybe you have a different version or an extension, which does extra work on top of the TypeScript language server?

- Clone the https://github.com/devoto13/sequelize-completion
- Run `npm ci` to install dependencies according to `package-lock.json`
- Open VS Code - `code .`
- Disable all extensions - Cmd + Shift + P - Disable all extensions for this Workspace
- Close VS Code and open it again - `code .`, verify that no extensions are enabled
- Attempt to get completion by typing `val` inside `@Column` annotation - no completion available
- Open `node_modules/sequelize-typescript/lib/annotations/Column.d.ts` and change last line to `export declare function Column(target: Object, propertyName: string, propertyDescriptor?: PropertyDescriptor): void;`
- Attempt to get completion by typing `val` inside `@Column` annotation - only `valueOf` is available in the completion list
- Open `node_modules/sequelize-typescript/lib/annotations/Column.d.ts` and remove or comment out the last line
- Attempt to get completion by typing `val` inside `@Column` annotation - the correct completion list of three items is shown

**Comment by RobinBuschmann** [comment] 2019-02-18 18:57
@devoto13 Ah, if typing `val` I'm also just getting `valueOf`, but (!) if i just press <kbd>ctrl</kbd>+<kbd>space</kbd> there (without typing `val`), I'm getting auto completion just fine. This is strange. Can you confirm this?

**Comment by devoto13** [comment] 2019-02-19 13:14
Yes, it is the same for me. It's my bad, sorry. I also have a full list on Ctlr+Space, but I had a long list of snippets on top, so I didn't notice the completion items at the very bottom. Good, now we have the same results at least 😄

And also now it sounds more like a bug/TypeScript limitation that `val` does not provide completion options. I'll try to investigate it a bit more to see what actually happens in communication with LSP and report back.

**Comment by RobinBuschmann** [comment] 2019-04-07 11:07
Let's close this issue. If you, @devoto13, find something out and think it makes sense to reopen, don't hesitate to do so

**Closed by RobinBuschmann** 2019-04-07 11:07 UTC

**Comment by devoto13** [comment] 2019-04-07 11:20
Sure! Sorry for disappearing on this, got a lot of other work on my plate and didn't have time to investigate it further.
