### ISSUE TITLE
underscored vs. model timestamps

### ISSUE THREAD

**Issue by cwhatley** [RobinBuschmann/sequelize-typescript#658] opened 2019-08-06 15:21 UTC
**Versions**

- sequelize: 5.12.3
- sequelize-typescript: 0.6.11
- typescript: 3.5.3

**I'm submitting a ...** 

[X ] bug report
[ ] feature request

**Actual behavior:**

The typing for Model has camel case for the timestamps in Model.d.ts which makes a reference to the timestamp fields named using underscores an error.

**Expected behavior:**

If underscores is set on the sequelize instance, then timestamps should also be referenceable via underscore names.

**Steps to reproduce:**

- Create a sequelize instance using underscores:true
- Create a model using timestamps:true
- Try to write code referring to created_at

**Comment by RobinBuschmann** [comment] 2019-08-06 18:33
Hey @cwhatley, thanks for reporting. First thing I've noticed: You are using sequelize@5.12.3 together with sequelize-typescript@0.6.11, which is not supported. For sequelize@>=5 sequelize-typescript@next is needed. Can you try it this way?

**Comment by cwhatley** [comment] 2019-08-15 20:03
I did try updating and still have to refer to the dates via "createdAt", for example.

**Comment by RobinBuschmann** [comment] 2019-09-02 18:27
Hey @cwhatley, didn't get your issue in the first place, sry for that. The `underscored` option doesn't make access to underscored properties possible but just converts the field values to from camelCase to underscored. See official docs: https://sequelize.org/master/manual/models-definition.html#configuration

Closing this, since it is expected behaviour

**Closed by RobinBuschmann** 2019-09-02 18:27 UTC
