### ISSUE TITLE
Relation does not exist (Foregin Key)

### ISSUE THREAD

**Issue by hamburml** [RobinBuschmann/sequelize-typescript#653] opened 2019-07-25 08:44 UTC
**Versions**

- sequelize: 5.10.2
- sequelize-typescript: 1.0.0-beta.3
- typescript 3.5.3

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

First time using sequelize and sequelize-typescriot. I have two models, device and measurement. A device can hav many measurements. A measurement is from exactly one device.

The Table "Devices" is created. The Table measurement can't be created. The error is that the relation "Devices" does not exist.

```
Executing (default): CREATE TABLE IF NOT EXISTS "test"."Measurements" ("id"   SERIAL , "deviceType" VARCHAR(255), "deviceId" INTEGER REFERENCES "Devices" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
sequelize.js:1182
(node:14524) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Relation »Devices« does not exist
```

It looks like the schema "test" is missing in the SQL. After INTEGER REFERENCES it should be "test"."Devices" shouldn't it?

**Expected behavior:**
Create the table :)

**Steps to reproduce:**

**Related code:**
```ts
@Table
export class Device extends Model<Device> 
{
    @Column
    euid: string;

    @Column
    type: String;

    @HasMany(() => Measurement)
    measurements: Measurement[];

}
```
```ts
@Table
export class Measurement extends Model<Measurement> 
{

    @Column
    deviceType: string;

    @ForeignKey(() => Device)
    @Column
    deviceId: number;
}

```

Main

```ts
async function preparePostgres()
{
    const sequelize =  new Sequelize({
        database: 'xxx',
        host: "localhost",
        port: 5432,
        dialect: 'postgres',
        username: 'xxx',
        password: 'xxx'
    });

    sequelize.addModels([Device, Measurement]);

    let schemas : any[] = await sequelize.showAllSchemas({});
    if (!schemas.includes("test"))
    {
        await sequelize.createSchema("test", {});
    }
    await sequelize.sync({schema: 'test'});
    

    return sequelize;
}

preparePostgres().then((sequelize) => {
    let test = Device.build({euid: "haha", type: "asdf"});
    test.save();
});
```

**Comment by RobinBuschmann** [comment] 2019-07-25 19:11
Hey @hamburml, this is because you're missing the `BelongsTo` relation on `Measurement `:

```ts
@Table
export class Measurement extends Model<Measurement> 
{

    @Column
    deviceType: string;

    @ForeignKey(() => Device)
    @Column
    deviceId: number;

    @BelongsTo(() => Device) 
     device: Device; 
}
```

Hope this helps!

**Comment by RobinBuschmann** [comment] 2019-08-02 17:50
@hamburml Did my answer solve your problem? Can we close this issue then?

**Comment by hamburml** [comment] 2019-08-06 06:15
@RobinBuschmann Haven't had time to test this. Will do in some hours.

**Comment by hamburml** [comment] 2019-08-12 07:55
@RobinBuschmann Didn't work :(
I added 

```js
    @BelongsTo(() => Device) 
    device: Device;
```

Still it does show 

```
Executing (default): CREATE TABLE IF NOT EXISTS "test"."Measurements" ("id"   SERIAL , "deviceType" VARCHAR(255), "time" TIMESTAMP WITH TIME ZONE, "measurementData" VARCHAR(255), "deviceId" INTEGER REFERENCES "Devices" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
```

**Comment by RobinBuschmann** [comment] 2019-08-12 11:24
Can you provide an example repo which reproduces the issue?

**Comment by RobinBuschmann** [comment] 2019-09-27 10:00
Closing this due to inactivity

**Closed by RobinBuschmann** 2019-09-27 10:00 UTC
