### ISSUE TITLE
TypeError: Class constructor Model cannot be invoked without 'new'

### ISSUE THREAD

**Issue by NickTaylor98** [RobinBuschmann/sequelize-typescript#472] opened 2018-10-15 14:10 UTC
I try to create new instance of my Model but have the following error:
```events.js:183
 throw er; // Unhandled 'error' event
       ^
 
TypeError: Class constructor Model cannot be invoked without 'new'
    at new Student (/service/dist/app/student/student.model.js:58:125)
    at Function.build (/service/node_modules/sequelize/lib/model.js:1976:12)
     at Function._target.(anonymous function) [as build] (/service/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
    at Function.create (/service/node_modules/sequelize/lib/model.js:2027:17)
     at Function._target.(anonymous function) [as create] (/service/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
     at /service/dist/app/metrics/action.js:66:69
    at Array.forEach (<anonymous>)
     at /service/dist/app/metrics/action.js:64:43
     at /service/node_modules/mongoose/lib/model.js:4499:16
     at process.nextTick (/service/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
     at process._tickCallback (internal/process/next_tick.js:181:9)`
```
Name of my model is Student. 
It's a code:
```
User.find({}, (err, users) => {
        if (err) throw new Error();
        users.forEach((user) => {
          if ((user as any).type === 2) {
            Student.create({
              uuid: user._id,
              last_name: (user as any).lastName,
              first_name: (user as any).firstName,
              creation_date: (user as any).createdAt,
              last_updated: (user as any).updatedAt,
            });
          }
        });
```
I use typescript-sequelize 0.6.6. Also I try to create the same instance by using `build` and `new`. The results of this actions are the same
My tsconfig.json
```{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "removeComments": true,
    "sourceMap": true,
    "outDir": "app",
    "rootDir": "src",
    "strictNullChecks": true,
    "noImplicitAny": true,
    "jsx": "react",
    "skipLibCheck": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "sourceRoot": "src",
    "allowJs": false,
    "experimentalDecorators": true,
    "mapRoot": "app",
    "moduleResolution": "node",
    "lib": ["dom", "es6", "es2015.promise", "es2016", "es2017", "es5"],
    "typeRoots": ["node_modules/@types"],
    "baseUrl": "./src",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "emitDecoratorMetadata": true
  },
  "exclude": [
    "node_modules",
    "app",
    "**/*.test.ts",
    "**/*.test.tsx"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": true,
  "buildOnSave": true,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by RobinBuschmann** [comment] 2018-10-16 06:10
@NickTaylor98 Your config looks good so far. Can you provide an example repo which reproduces the issue?

**Comment by NickTaylor98** [comment] 2018-10-16 10:52
@RobinBuschmann , unfortunately no, because it's a not open source project. You can asks me to show some parts of code, but not whole code

**Comment by NickTaylor98** [comment] 2018-10-16 11:00
@RobinBuschmann also I use babel 6.24.1. The file .babelrc is the following
```
{
  "presets": [
    "env",
    "es2015",
    "stage-2"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ],
  "sourceMaps": "both"
}

```

**Comment by RobinBuschmann** [comment] 2018-10-16 15:32
Hey @NickTaylor98, you don’t need to put productive code in the example repo, just a simple example which reproduces the problem and gives me the ability to check the issue. I can hardly reproduce your problem without it...

**Comment by rochapablo** [comment] 2018-10-30 21:55
I'm getting:

```
[Node] TypeError: Class constructor Product cannot be invoked without 'new'
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:114:47)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at node_modules\class-transformer\TransformOperationExecutor.js:33:41
[Node]     at Array.forEach (<anonymous>)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:30:19)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at _loop_1 (node_modules\class-transformer\TransformOperationExecutor.js:154:45)
[Node]     at TransformOperationExecutor.transform (node_modules\class-transformer\TransformOperationExecutor.js:178:17)
[Node]     at ClassTransformer.classToPlain (node_modules\class-transformer\ClassTransformer.js:9:25)
[Node]     at Object.classToPlain (node_modules\class-transformer\index.js:12:29)
[Node]     at ExpressDriver.BaseDriver.transformResult (node_modules\routing-controllers\driver\BaseDriver.js:33:42)
[Node]     at ExpressDriver.handleSuccess (node_modules\routing-controllers\driver\express\ExpressDriver.js:225:23)
[Node]     at node_modules\routing-controllers\RoutingControllers.js:128:61
[Node] GET /products 500 81.439 ms - -
```

```
return await Product.findAll({
      include: [
        { model: Category },
        { model: Image }
      ],
      // raw: true
    });
```

```
"sequelize": "^4.41.0",
 "sequelize-typescript": "^0.6.6",
```

```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": "ESNEXT",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "strictNullChecks": true,
        "noUnusedLocals": true,
        "pretty": true,
        "skipLibCheck": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src/**/*"
    ]
}
```

**Comment by RobinBuschmann** [comment] 2018-10-31 07:08
Hey @rochapablo, this is definitely an issue with class-transformer - Which Version are you using of class-transformer?

**Comment by rochapablo** [comment] 2018-11-01 22:49
I'm not, I thought that sequelize-typescript was using it. =/

**Comment by RobinBuschmann** [comment] 2018-11-02 07:29
@rochapablo In order to find out which other package needs class-transformer, you can navigate to `node_modules/class-transformer/package.json` of your project and check the `_requiredBy` property.

**Comment by rochapablo** [comment] 2018-11-04 11:59
Thanks, `routing-controllers` seems to be the villain.

**Comment by RobinBuschmann** [comment] 2018-11-15 08:02
Closing this issue due to no further information were provided by reporter

**Closed by RobinBuschmann** 2018-11-15 08:02 UTC

**Comment by acuntex** [comment] 2018-12-18 14:42
@rochapablo how did you fix the villain?

**Comment by rochapablo** [comment] 2018-12-27 09:46
@acuntex I fix by setting `{ classTransformer: false }` in https://github.com/typestack/routing-controllers config.

**Comment by azaeng04** [comment] 2019-01-01 15:04
Hi @RobinBuschmann 

I have been receiving this exact same issue with Wallaby js.

The `ExpenseGroup.model.ts`

```'use strict';

import { Table, Model, Column, DataType, CreatedAt, UpdatedAt, DeletedAt } from 'sequelize-typescript';

@Table
export class ExpenseGroup extends Model<ExpenseGroup>{

  @Column({ type: DataType.STRING, allowNull: false })
  public name: string;

  @Column({ type: DataType.STRING, allowNull: false })
  public description: string;

  @CreatedAt
  public createdAt: Date;

  @UpdatedAt
  public updatedAt: Date;

  @DeletedAt
  public deletedAt: Date;
};
```

The test:

```
describe('Expense Group CRUD', () => {
    beforeAll(async () => {
        await sequelize.sync({ force: true });
    })
    test.only('can create an Expense Group', async () => {
        const _expenseGroup = await ExpenseGroup.create(expenseGroup);

        // expect(_expenseGroup).toHaveProperty('id');
        // expect(_expenseGroup).toMatchObject(expenseGroup);
    });
....
```

The error that Wallaby js is throwing.

```​​​​​1 failing test, 0 passing (only executed src/tests/integration/models/expenseGroupCrud.test.ts)​​​​​
  
  ​​​​Expense Group CRUD can create an Expense Group​​​​ ​​​[34 ms]​​​​
    ​​​​
    ​​TypeError: Class constructor Model cannot be invoked without 'new'​​
      at new apply ​src/models/ExpenseGroup.model.ts:6​
      at Object.create ​src/tests/integration/models/expenseGroupCrud.test.ts:12:8​
      at Object.__awaiter ​src/tests/integration/models/expenseGroupCrud.test.ts:11:4​
```

`My tsconfig`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "esnext",
        "allowJs": true,
        "noImplicitAny": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

Help would be much appreciated.

**Comment by azaeng04** [comment] 2019-01-02 14:46
@RobinBuschmann I do not see the class transformer or routing controllers package under my node_modules.

**Comment by azaeng04** [comment] 2019-01-02 15:10
I have noticed that it is only throwing this error when I execute any function that wants to create the necessary object.

**Comment by RobinBuschmann** [comment] 2019-01-03 16:23
@azaeng04 Are you really, really sure, that `es6+` is used? I see your tsconfig looks correct (`"target": "esnext",`), but probably it is ignored for compilation somehow. Otherwise, can you provide an example repo which reproduces the issue, so that I can have a look at it?
