### ISSUE TITLE
Support for Array types

### ISSUE THREAD

**Issue by mannol** [RobinBuschmann/sequelize-typescript#594] opened 2019-04-04 09:30 UTC
If you define a column like:
```ts
@Column(DataType.ARRAY(DataType.STRING))
myCol: string[];
```

You'll get the error saying: 
```
error TS2559: Type 'ArrayDataType<AbstractDataTypeConstructor>' has no properties in common with type 'Partial<ModelAttributeColumnOptions>'.
```

**Comment by devoto13** [comment] 2019-04-04 09:46
Seems to be a regression in one of the latest releases. 

You can workaround it it by doing `@Column({ type: DataType.ARRAY(DataType.STRING) })` in the meantime.

**Comment by RobinBuschmann** [comment] 2019-04-14 10:24
@mannol Thanks for bringing this up. Does this happen with sequelize-typescript@canary?

**Comment by mannol** [comment] 2019-04-14 11:08
@RobinBuschmann no problem. Thanks for this library!

On your question, I believe I installed the lib via `yarn add sequelize-typescript@canary` like 2 weeks ago. `package.json` shows I'm using version `"^1.0.0-alpha.9` of this lib with sequelize version `^5.2.9`.

**Comment by RobinBuschmann** [comment] 2019-04-14 11:14
@mannol Thanks. I wanted to make sure, that @devoto13's fix solves the issue. Since he made one for sequelize-typescript@1.

**Comment by mannol** [comment] 2019-04-14 11:18
@RobinBuschmann sweet! Looks promising :+1:

**Comment by RobinBuschmann** [comment] 2019-04-22 09:11
Closing this, since it was fixed with `sequelize-typescript@1.0.0-beta.1`

**Closed by RobinBuschmann** 2019-04-22 09:11 UTC

**Comment by ihoryan** [comment] 2020-02-18 12:03
I'm trying to define array property and getting the error.
`\app\node_modules\sequelize-typescript\dist\model\shared\model-service.js:63
    throw new Error(`Specified type of property '${propertyName}'
          ^
source-map-support.js:419
Error: Specified type of property 'permissions'
            cannot be automatically resolved to a sequelize data type. Please
            define the data type manually`

sequelize-typescript@6.7.0
