### ISSUE TITLE
sequelize-typescript 2.0.0-beta.0 + sequelize 6.3.4 associations bug

### ISSUE THREAD

**Issue by oktapodia** [RobinBuschmann/sequelize-typescript#828] opened 2020-08-19 13:25 UTC
**Versions**

- sequelize: 6.3.4
- sequelize-typescript: 2.0.0-beta.0
- typescript: 3.9.7

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Actual behavior:**

Using the relations does not seem to work with that version, getting the error on all relations

  node_modules/sequelize-typescript/dist/model/shared/model-class-getter.d.ts:2:40
    2 export declare type ModelClassGetter = (returns?: void) => typeof Model;
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**Expected behavior:**
<!-- Describe what the behavior would be without the bug. -->
The same code is perfectly working on the version 1~ and sequelize 5~

**Steps to reproduce:**
<!--  Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application. -->

You can try with the https://github.com/RobinBuschmann/sequelize-typescript-example with configuring both versions

**Related code:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

- A sample application via GitHub (Best option, since its much easier for us to investigate, so that we can come back to you more recently)
- A code snippet below (Please make sure, that the snippet at least includes tsconfig and the sequelize options)

-->
```ts
insert short code snippets here
```

**Comment by jgburet** [comment] 2020-10-13 09:38
already reported https://github.com/RobinBuschmann/sequelize-typescript/issues/813

**Comment by Divlo** [comment] 2021-01-17 21:32
Duplicate of #813.

**Closed by Divlo** 2021-01-17 21:32 UTC
